# MoshidonQX Custom Configuration
# ----------------------------------------------------

# 1. Custom Application ID (Package Name / Application ID)
# Feel free to change this to any package name you want, e.g. com.myusername.moshidon
custom_application_id=org.joinmastodon.android.qx

# 2. Custom Application Name (App Name)
# This will be displayed on the phone launcher screen
custom_app_name=MoshidonQX

# 3. Maximum Image/Attachment Upload Limit (Default is 12)
max_images_limit=12
